"""Add column Status for links

Revision ID: 03bca0c4c368
Revises: da813dae1525
Create Date: 2023-10-31 16:04:59.681302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bca0c4c368'
down_revision = 'da813dae1525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linksmodel', sa.Column('status', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linksmodel', 'status')
    # ### end Alembic commands ###
