"""First migration

Revision ID: 79035e6e5c5c
Revises: 
Create Date: 2023-10-31 15:34:07.507493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79035e6e5c5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linksmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=2048), nullable=False),
    sa.Column('short', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short')
    )
    op.create_index(op.f('ix_linksmodel_timestamp'), 'linksmodel', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linksmodel_timestamp'), table_name='linksmodel')
    op.drop_table('linksmodel')
    # ### end Alembic commands ###
