"""enter uuid4

Revision ID: 7a3cf40c5ce7
Revises: 896b5fd864db
Create Date: 2023-11-11 13:59:51.883234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3cf40c5ce7'
down_revision = '896b5fd864db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
