"""enter uuid

Revision ID: 896b5fd864db
Revises: 9034f9bdb85e
Create Date: 2023-11-11 13:32:37.210437

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '896b5fd864db'
down_revision = '9034f9bdb85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linksmodel', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('linksmodel_user_id_fkey', 'linksmodel', type_='foreignkey')
    op.create_foreign_key(None, 'linksmodel', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('querydatamodel', 'short_link_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('querydatamodel_short_link_id_fkey', 'querydatamodel', type_='foreignkey')
    op.create_foreign_key(None, 'querydatamodel', 'linksmodel', ['short_link_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'querydatamodel', type_='foreignkey')
    op.create_foreign_key('querydatamodel_short_link_id_fkey', 'querydatamodel', 'linksmodel', ['short_link_id'], ['id'])
    op.alter_column('querydatamodel', 'short_link_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'linksmodel', type_='foreignkey')
    op.create_foreign_key('linksmodel_user_id_fkey', 'linksmodel', 'user', ['user_id'], ['id'])
    op.alter_column('linksmodel', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
