"""add field url_short in table links

Revision ID: 9034f9bdb85e
Revises: d4980538df41
Create Date: 2023-11-07 09:31:09.878784

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '9034f9bdb85e'
down_revision = 'd4980538df41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linksmodel', sa.Column('url_short', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linksmodel', 'url_short')
    # ### end Alembic commands ###
