"""add table query_data

Revision ID: d4980538df41
Revises: 4f1371890ca9
Create Date: 2023-11-06 12:50:24.500042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4980538df41'
down_revision = '4f1371890ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('querydatamodel',
    sa.Column('short_link_id', sa.Integer(), nullable=True),
    sa.Column('ip_client', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['short_link_id'], ['linksmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_querydatamodel_timestamp'), 'querydatamodel', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_querydatamodel_timestamp'), table_name='querydatamodel')
    op.drop_table('querydatamodel')
    # ### end Alembic commands ###
