"""Add column Password for links

Revision ID: da813dae1525
Revises: 79035e6e5c5c
Create Date: 2023-10-31 15:53:17.704805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da813dae1525'
down_revision = '79035e6e5c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linksmodel', sa.Column('password', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'linksmodel', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'linksmodel', type_='unique')
    op.drop_column('linksmodel', 'password')
    # ### end Alembic commands ###
